export const errors = {};

export const DATE_FORMAT = "MMM Do YY";

export const tokenStorageLabel = "itu-token"

export const actions = {
  user: {
    LOGIN: "USER_LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",

    LOGOUT: "USER_LOGOUT",
    LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
    LOGOUT_FAIL: "USER_LOGOUT_FAIL",

    FETCH_USER: "FETCH_USER",
    FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
    FETCH_USER_FAIL: "FETCH_USER_FAIL"
  },
  students: {
    FETCH: "FETCH_STUDENTS",
    FETCH_FAIL: "FETCH_FAIL_STUDENTS",
    FETCH_SUCCESS: "FETCH_SUCCESS_STUDENTS",
    
    FETCH_STUDENT_COURSE: "FETCH_STUDENT_COURSE",
    FETCH_STUDENT_COURSE_FAIL: "FETCH_STUDENT_COURSE_FAIL",
    FETCH_STUDENT_COURSE_SUCCESS: "FETCH_STUDENT_COURSE_SUCCESS",

    UPDATE_STUDENT: "UPDATE_STUDENT",
    UPDATE_STUDENT_FAIL: "UPDATE_STUDENT_FAIL",
    UPDATE_STUDENT_SUCCESS: "UPDATE_STUDENT_SUCCESS",
    
    SEARCH_COURSES: "SEARCH_COURSES",
    SEARCH_COURSES_FAIL: "SEARCH_COURSES_FAIL",
    SEARCH_COURSES_SUCCESS: "SEARCH_COURSES_SUCCESS",
  },
  
  departments: {
    FETCH_FACULTIES: "FETCH_FACULTIES",
    FETCH_FACULTIES_FAIL: "FETCH_FACULTIES_FAIL",
    FETCH_FACULTIES_SUCCESS: "FETCH_FACULTIES_SUCCESS",

    FETCH_LECTURERS: "FETCH_LECTURERS",
    FETCH_LECTURERS_FAIL: "FETCH_LECTURERS_FAIL",
    FETCH_LECTURERS_SUCCESS: "FETCH_LECTURERS_SUCCESS",

    DELETE_LECTURER: "DELETE_LECTURER",
    DELETE_LECTURER_FAIL: "DELETE_LECTURER_FAIL",
    DELETE_LECTURER_SUCCESS: "DELETE_LECTURER_SUCCESS",

    ADD_LECTURER: "ADD_LECTURER",
    ADD_LECTURER_FAIL: "ADD_LECTURER_FAIL",
    ADD_LECTURER_SUCCESS: "ADD_LECTURER_SUCCESS",
  },
  homeworks: {
    FETCH_HOMEWORKS: "FETCH_HOMEWORKS",
    FETCH_HOMEWORKS_FAIL: "FETCH_HOMEWORKS_FAIL",
    FETCH_HOMEWORKS_SUCCESS: "FETCH_HOMEWORKS_SUCCESS",
    ADD_HOMEWORK: "ADD_HOMEWORK",
    ADD_HOMEWORK_FAIL: "ADD_HOMEWORK_FAIL",
    ADD_HOMEWORK_SUCCESS: "ADD_HOMEWORK_SUCCESS",
    DELETE_HOMEWORK: "DELETE_HOMEWORK",
    DELETE_HOMEWORK_FAIL: "DELETE_HOMEWORK_FAIL",
    DELETE_HOMEWORK_SUCCESS: "DELETE_HOMEWORK_SUCCESS"
  },
  chatgroups:{
    FETCH_CHATGROUPS: "FETCH_CHATGROUPS",
    FETCH_CHATGROUPS_FAIL: "FETCH_CHATGROUPS_FAIL",
    FETCH_CHATGROUPS_SUCCESS: "FETCH_CHATGROUPS_SUCCESS",
    FETCH_CHATGROUP_MEMBERS: "FETCH_CHATGROUP_MEMBERS",
    FETCH_CHATGROUP_MEMBERS_FAIL: "FETCH_CHATGROUP_MEMBERS_FAIL",
    FETCH_CHATGROUP_MEMBERS_SUCCESS: "FETCH_CHATGROUP_MEMBERS_SUCCESS",
    CREATE_CHATGROUP: "CREATE_CHATGROUP",
    CREATE_CHATGROUP_FAIL: "CREATE_CHATGROUP_FAIL",
    CREATE_CHATGROUP_SUCCESS: "CREATE_CHATGROUP_SUCCESS"
  }
};

export const apiUrl = "http://881ce9ad.ngrok.io/";
